"""Pydantic schemas for Instagram events and intervention statuses."""

from datetime import datetime
from typing import Optional
import uuid

from pydantic import BaseModel, ConfigDict, Field


class InstagramEventCreate(BaseModel):
    event_type: str = Field(
        default="instagram_open",
        description="Event type, e.g. instagram_open or instagram_close",
    )
    timestamp: Optional[datetime] = Field(
        default=None,
        description="Client occurrence timestamp (defaults to server UTC now)",
    )
    session_id: Optional[str] = Field(
        default=None,
        description="Client session identifier for tracking continuous usage sessions",
    )
    client_event_id: Optional[str] = Field(
        default=None,
        description="Idempotency key generated by client to prevent duplicate event creation",
    )


class InstagramEventResponse(BaseModel):
    success: bool = True
    event_id: uuid.UUID
    intervention_triggered: bool
    eligible_laptops_count: int
    message: Optional[str] = None


class InstagramEventDetail(BaseModel):
    model_config = ConfigDict(from_attributes=True)
    id: uuid.UUID
    user_id: uuid.UUID
    device_id: uuid.UUID
    event_type: str
    client_event_id: Optional[str] = None
    session_id: Optional[uuid.UUID] = None
    occurred_at: datetime
    created_at: datetime
