"""Pairing dialog window for associating the laptop with NoInsta user account."""

import logging
import socket
from typing import Callable, Optional, Tuple

from PySide6.QtCore import Qt
from PySide6.QtWidgets import (
    QDialog,
    QHBoxLayout,
    QLabel,
    QLineEdit,
    QPushButton,
    QVBoxLayout,
    QWidget,
)

logger = logging.getLogger(__name__)


class PairingDialog(QDialog):
    """Dialog allowing user to enter pairing code generated by the NoInsta phone app."""

    def __init__(
        self,
        pair_callback: Callable[[str, str], Tuple[bool, str]],
        default_server_url: str = "https://noinsta.platesight.in",
        parent: Optional[QWidget] = None,
    ):
        super().__init__(parent)
        self.pair_callback = pair_callback
        self.default_server_url = default_server_url

        self.setWindowTitle("NoInsta - Device Pairing")
        self.setModal(True)
        self.setFixedWidth(400)
        self._init_ui()

    def _init_ui(self) -> None:
        self.setStyleSheet("""
            QDialog {
                background-color: #1E1E1E;
                color: #FFFFFF;
            }
            QLabel {
                color: #E0E0E0;
                font-size: 13px;
            }
            QLabel#TitleLabel {
                color: #FFFFFF;
                font-size: 20px;
                font-weight: bold;
            }
            QLabel#StatusLabel {
                color: #FFA726;
                font-size: 12px;
            }
            QLineEdit {
                background-color: #2C2C2C;
                color: #FFFFFF;
                border: 1px solid #444444;
                border-radius: 6px;
                padding: 8px 12px;
                font-size: 14px;
            }
            QLineEdit:focus {
                border: 1px solid #E1306C;
            }
            QPushButton#PairButton {
                background-color: #E1306C;
                color: #FFFFFF;
                font-weight: bold;
                padding: 10px;
                border-radius: 6px;
                border: none;
                font-size: 14px;
            }
            QPushButton#PairButton:hover {
                background-color: #C13584;
            }
            QPushButton#CancelButton {
                background-color: #333333;
                color: #AAAAAA;
                padding: 10px;
                border-radius: 6px;
                border: none;
            }
            QPushButton#CancelButton:hover {
                background-color: #444444;
            }
        """)

        layout = QVBoxLayout(self)
        layout.setContentsMargins(24, 24, 24, 24)
        layout.setSpacing(14)

        # Title
        title = QLabel("NOINSTA")
        title.setObjectName("TitleLabel")
        title.setAlignment(Qt.AlignmentFlag.AlignCenter)
        layout.addWidget(title)

        subtitle = QLabel("Pair this laptop to your NoInsta account")
        subtitle.setAlignment(Qt.AlignmentFlag.AlignCenter)
        layout.addWidget(subtitle)

        layout.addSpacing(8)

        # Pairing code input
        layout.addWidget(QLabel("Enter 6-character Pairing Code:"))
        self.code_input = QLineEdit()
        self.code_input.setPlaceholderText("e.g. A7K9Q2")
        self.code_input.setMaxLength(32)
        layout.addWidget(self.code_input)

        # Device name input
        layout.addWidget(QLabel("Device Name:"))
        self.name_input = QLineEdit()
        self.name_input.setText(socket.gethostname())
        layout.addWidget(self.name_input)

        # Status label
        self.status_label = QLabel("")
        self.status_label.setObjectName("StatusLabel")
        self.status_label.setWordWrap(True)
        self.status_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        layout.addWidget(self.status_label)

        layout.addSpacing(6)

        # Buttons
        btn_layout = QHBoxLayout()
        self.cancel_btn = QPushButton("Cancel")
        self.cancel_btn.setObjectName("CancelButton")
        self.cancel_btn.clicked.connect(self.reject)
        btn_layout.addWidget(self.cancel_btn)

        self.pair_btn = QPushButton("Pair Device")
        self.pair_btn.setObjectName("PairButton")
        self.pair_btn.clicked.connect(self._on_pair_clicked)
        btn_layout.addWidget(self.pair_btn)

        layout.addLayout(btn_layout)

        self.code_input.returnPressed.connect(self._on_pair_clicked)

    def _on_pair_clicked(self) -> None:
        """Handle Pair Device button click."""
        code = self.code_input.text().strip().upper()
        if not code:
            self.status_label.setText("Please enter a pairing code.")
            return

        name = self.name_input.text().strip() or socket.gethostname()

        self.pair_btn.setEnabled(False)
        self.code_input.setEnabled(False)
        self.status_label.setText("Contacting server...")

        try:
            success, message = self.pair_callback(code, name)
            if success:
                self.status_label.setStyleSheet("color: #66BB6A;")
                self.status_label.setText(message or "Device paired successfully!")
                self.accept()
            else:
                self.status_label.setStyleSheet("color: #EF5350;")
                self.status_label.setText(message or "Pairing failed.")
        except Exception as exc:
            logger.error("Pairing request failed: %s", exc)
            self.status_label.setText(f"Error: {exc}")
        finally:
            self.pair_btn.setEnabled(True)
            self.code_input.setEnabled(True)
